### ISSUE TITLE
Not fetching correct package

### ISSUE THREAD

**Issue by nicklauslittle-gov** [airpwr/airpwr#45]
I tried the following (using version 0.4.27):

```powershell
PS C:\WINDOWS\system32> pwr sh jdk:7
pwr: fetching jdk:17.0.4
pwr: fetched 1 package (jdk:17.0.4)
pwr: using jdk:17.0.4
```

Notice it fetched version 17 when I requested 7. Is this correct? I would expect that if a JDK 7 package doesn't exist then I would get an error (maybe with a suggestion or question about using JDK 17). Maybe it's just finding the latest version that contains a 7?

**Comment by tbateson** [comment]
Confirmed this is a bug.

```
PS > pwr which jdk:7
jdk:17.0.4 
```
