### ISSUE TITLE
Lock mechanism broken

### ISSUE THREAD

**Issue by nicklauslittle-gov** [airpwr/airpwr#53]
It appears the lock mechanism to prevent multiple simultaneous updates is not working correctly. I receive the following messages when running in multiple terminals simultaneously. (Ignore the errors.)

Terminal 1:

> ```powershell
> PS C:\Users\XXX> pwr sh; pwr load cmake-converter, llvm
> pwr: fetching erlang:25.1.1
> pwr: command 'curl.exe' finished with non-zero exit value 56
> ```

Terminal 2:

> ```powershell
> PS C:\Users\XXX> pwr sh git
> New-Item : The file 'C:\Users\XXX\AppData\Roaming\pwr\pwr.lock' already exists.
> At C:\Users\XXX\AppData\Roaming\pwr\cmd\pwr.ps1:1057 char:3
> +         New-Item $PwrLock -ItemType File -WhatIf:$false | Out-Null
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (C:\Users\XXX...ng\pwr\pwr.lock:String) [New-Item], IOException
>     + FullyQualifiedErrorId : NewItemIOError,Microsoft.PowerShell.Commands.NewItemCommand
>
> pwr: fetching git:2.38.0
> pwr: command 'curl.exe' finished with non-zero exit value 6
> ```

Terminal 1:

> ```powershell
> pwr: fetching llvm:15.0.2
> Write-PwrFatal : pwr: command 'curl.exe' finished with non-zero exit value 56
> At C:\Users\XXX\AppData\Roaming\pwr\cmd\pwr.ps1:324 char:3
> +         Write-PwrFatal "command 'curl.exe' finished with non-zero exi ...
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-PwrFatal
>
> Remove-Item : Cannot find path 'C:\Users\XXX\AppData\Roaming\pwr\pwr.lock' because it does not exist.
> At C:\Users\XXX\AppData\Roaming\pwr\cmd\pwr.ps1:1065 char:3
> +         Remove-Item $PwrLock -WhatIf:$false
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (C:\Users\XXX...ng\pwr\pwr.lock:String) [Remove-Item], ItemNotFoundException
>     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
> ```

**Comment by troyaf** [comment]
I've seen similar things. I'll review how locking is done.
