### ISSUE TITLE
Issues with "load"

### ISSUE THREAD

**Issue by nicklauslittle-gov** [airpwr/airpwr#54]
Not a big deal, but I've noticed a couple of issues with `pwr load`. The first issue is that it doesn't display in `pwr:` in blue like `pwr sh` does. Secondly, if something fails during a `pwr load`, I get kicked out of my existing `pwr sh` even though there is no issue with my current `pwr sh`.

**Comment by troyaf** [comment]
Okay. I'm gonna recreate this and see if there's an easy fix.

**Comment by troyaf** [comment]
I think I have a fix for the `pwr:` coloring.

I failed to reproduce or find the relevant logic why a `load` would kill your shell. 
Will you give some more detail? Is it resetting everything about the environment vars?

**Comment by nicklauslittle-gov** [comment]
I'm pretty sure it happened when one of the `load` packages had to update, but failed to download. I noticed the `pwr:` prompt was gone, and I couldn't run commands. I didn't check anything else beyond that. It happened a couple weeks ago, and was on an older version. Maybe we just close this out and if it happens again I can post the log?

**Comment by troyaf** [comment]
Sounds good. Reopen if you see it again.
