### ISSUE TITLE
Color Issue

### ISSUE THREAD

**Issue by nicklauslittle** [airpwr/airpwr#57]
I noticed that the `pwr:` color is different at different times. For example if I run ` pwr sh ...` (notice the space at the beginning), it is not blue for the `using ...` statements. Likewise with something like `pwr sh ...; pwr load ...` for the `loaded ...` statements. I traced it down to this line:

```powershell
$WriteToHost = ($MyInvocation.ScriptLineNumber -eq 1) -and ($MyInvocation.OffsetInLine -eq 1) -and ($MyInvocation.PipelineLength -eq 1)
```

I was wondering why this is necessary and if there is a different way to determine this?

**Comment by troyaf** [comment]
Yes. See https://github.com/airpwr/airpwr/pull/56

**Comment by nicklauslittle** [comment]
Obsoleted by #75.
