### ISSUE TITLE
pwr 0.6

### ISSUE THREAD

**Issue by troyaf** [airpwr/airpwr#74]
# Project Management

## Distribution

`pwr 0.6` will be published as a PowerShell module to https://www.powershellgallery.com/

Once published, built-in `*-Module` commands will be used to install and manage the module.

The module will export `pwr` as an alias to the entry cmdlet.

## Code

`pwr 0.6` will have multiple source files for better maintenance.
A top level `build.ps1` will create the single `.psm1` file and associated `.psd1` for module distribution.

[Pester](https://pester.dev/) will be used as a test framework and will provide coverage metrics.

# Package Management

`pwr 0.6` will continue to use Docker as its backend format and distribution mechanism.

However, instead of relying on system executables, `pwr 0.6` will use [System.Net.Http.HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-7.0) to pull data from Docker's registry, [IO.Compression.GzipStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.gzipstream?view=net-7.0) to decompress the fetched `.tar.gz`, and custom code to extract the `.tar` because [System.Formats.Tar](https://learn.microsoft.com/en-us/dotnet/api/system.formats.tar?view=net-7.0) is only available in .NET 7 and later.

## Tracking

`pwr 0.6` employs a new philosophy for tracking packages.

A package's digest is first-class and can be reference by multiple tags. When a package has multiple tag references, removing the tag only removes the reference. Once the reference count is zero, a `remove` performs a reclusive deletion of the backing data.

When a tag resolves to a new digest on `pull`, the tag is updated to that digest, and the old digest has its reference count decremented. Should the reference count reach zero on a `pull`, it's data will not be deleted until a call to `prune` or `remove`.

This system closely follows Docker's behavior for local image management.

## Progress

`pwr 0.6` reports progress for downloading, decompressing, and extracting packages using Unicode Block Elements.

HTTP requests utilize the `Range` header to resume downloads previously cancelled. Chunking to support proxy policies is not yet implemented.

## Pull Policy

Previously, the latest of some specified version of a package was downloaded always. Only `-Offline` modified this behavior.

`pwr 0.6` will behave similarly to kubernetes' image pull policy.

### IfNotPresent (default)
The package is pulled only if it is not already present locally.
### Always
Every time `pwr pull` is invoked, it queries the remote registry to resolve the name to an image [digest](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier). If the package with that exact digest cached locally, `pwr` uses its cached packaged; otherwise, the `pwr` pulls the package with the resolved digest.
### Never
`pwr` does not try fetching the package. If the package is somehow already present locally, `pwr` uses that package; otherwise, the command fails.

# CLI

`pwr 0.6` has a streamlined interface with no ad-hoc flags.

	pwr version, v      outputs the 3-part version of the module
	pwr list            outputs a list of installed packages
	pwr remote list     outputs a list of remote packages
	pwr pull            installs packages
	pwr load            loads packages into the PowerShell session
	pwr exec            runs a user-defined scriptblock in a managed PowerShell session state
	pwr run             runs a user-defined scriptblock
	pwr prune           deletes unreferenced packages
	pwr remove, rm      untags and deletes packages

## `pwr list`, `pwr remote list`

Each `list` command will output a .NET object which can be manipulated, sorted, and searched to the user's desire.

Previously, `Format-Table` was used to pretty print, but the output was unusable for further programmatic inspection.

## `pwr exec`

`pwr exec` replaces `pwr shell` and `pwr exit`.

```PowerShell
try {
	pwr sh go, git
	$ref = git describe --always
	go build ...
} finally {
	pwr exit
}
```
is equivalent to
```PowerShell
pwr exec go, git {
	$ref = git describe --always
	go build ...
}
```

# Project File

`pwr 0.6` will use a PowerShell file instead of JSON to describe a project.

```PowerShell
$script:PwrPackages = 'git', 'jdk:11', 'gradle'

# other variable decls
# other script init

function PwrInstall {
	# do install...
}

function PwrBuild {
	param (
		[string]$SomeParam
	)
	$installed = ...
	if (-not $installed) {
		PwrInstall
	}
	# do build...
}
```

The project file is dot sourced and analyzed for functions and variables starting with `Pwr`.
- `Pwr` functions are invoked when specified in the `run` command. Arguments are passed to the defined function and handled accordingly.
- `Pwr` variables alter the behavior of associated commands.

Example invocation of the `PwrBuild` function:
```PowerShell
pwr run build 'some build arg'
```

**Comment by troyaf** [comment]
# How `pwr 0.6` Addresses Open PRs

## `#72 Remove use of curl.exe`

Implemented. Uses `Net.Http.HttpClient`.

## `#71 Add download resume and recover`

Partially implemented. Used `Range` header to resume download, but chunking still needed if that's the only way around the proxy counter.

## `#69 Add initialization scripts to configuration`

Will be implemented. New project file behavior allows for arbitrary initialization.

## `#68 Add -ScriptBlock Option`

Implemented as `pwr exec <scriptblock>`.

## `#63 Add Auto-pruning`

Not implemented. I remain skeptical on the value of this feature. `pwr prune` is a nice command, just call it? 🤷‍♂️ Maybe we can argue this more with defined use cases.

## `#56 Remove offset when considering write to host`

Not implemented. Our philosophy on writing to output streams was kind of a mess. The new design outputs to the object stream when there is data to return, and only in a few places are there writes to the info stream for user awareness. I see this as OBE.

## `#51 Add prune command and rework config`

Implemented. Prune is in and there is no user specified config files. All `pwr` metadata is now in a single file and is not to be viewed or manipulated by a user.

## `#37 Add pwr.sum with sha256 digests`

Not implemented. `pwr` is now digest focused, but the use cases of a sum file are still a bit undetermined and need more thought before execution.

**Comment by troyaf** [comment]
# How `pwr 0.6` Addresses Open Issues without an Associated PR

## `#73 Recommended install method doesn't work behind firewall`

New distribution mechanism on psgallery has a chance to solve this. Will investigate soon.

## `#57 Color Issue`

Related to the output stream mess. OBE moving forward.

## `#34 Add indication of download status`

Implemented.

## `#20 Load from docker image`

Still todo. The `file:///` mechanism is removed, but I am still deciding between a single file container `.tar` or analyzing the local docker cache.

## `#5 Check authentication`

OBE. Only the official registry is supported until a need arises to change this.

**Comment by nicklauslittle** [comment]
> #63 Add Auto-pruning
> Not implemented. I remain skeptical on the value of this feature. pwr prune is a nice command, just call it? 🤷‍♂️ Maybe we can argue this more with defined use cases.

The main value of this feature is that it allows old packages to be phased out based on elapsed time. Without it/currently, I would basically run a `pwr prune` whenever I see a package is eligible for pruning. This would remove the old version immediately. If I had another `pwr` session open in another window, it would no longer function. Or, if I noticed a couple hours/days later that the new version doesn't work the same as an older version, then I would have to redownload the old version to get the old functionality.

With this feature, I could set the auto-pruning value to 5/7/30/etc days. During that time, I could verify correct functionality of new versions, not have to worry about manual pruning after a given amount of time, and allow multiple open `pwr` windows to continue to work correctly.

Those are my arguments for it. (Not to mention that it defaults to `off`, which is the same as the current, manual pruning method.)

**Comment by tbateson** [comment]
Don't think it was mentioned, but the new location of `pwr` is in `$env:LocalAppData`. This is more correct in my view since the purpose of `AppData/Roaming` is for computers on a network to be synced. Given the size of some of the packages, they should probably not be synced in such an environment.

**Comment by nicklauslittle** [comment]
If version 0.6 is going to be a major overhaul, you might consider adding in some functionality to permanently enable certain commands in a `PowerShell` prompt (and maybe even a `cmd` prompt). I have recently been working on something like this (https://github.com/nicklauslittle/airpwr/compare/pwr-install~1...pwr-install), because I want `git` to always be on the path, even though I am constantly switch between projects (and `pwr sh`) in various prompts.

With this, I can basically copy `pwr-install.ps1` and `empty-pkg` into the `$env:AppData\pwr\cmd` directory and then run `pwr-install git gitk` to get `gitk` on my path permanently via a `gitk.bat` file in the `cmd` directory. (I chose batch files, so it would work outside `PowerShell`.) I chose not to implement it inside `pwr` because it would've involved quite a few modifications and added in a new command and command-specific options. But, if it could be implemented there, it might be more maintainable. If not, I can just use the current solution.

Some of my design goals were:
- Commands available from within PowerShell
  - Can be overridden by a `pwr sh`
- Commands available from a `cmd` shell to support tools that call other commands via command line or `CreateProcess()`
- Support exit codes and pipes
- Don't clear environment variables when called, since some commands may be configured by them

**Comment by nicklauslittle** [comment]
> Don't think it was mentioned, but the new location of `pwr` is in `$env:LocalAppData`. This is more correct in my view since the purpose of `AppData/Roaming` is for computers on a network to be synced. Given the size of some of the packages, they should probably not be synced in such an environment.

As long as everything still works in that location, then that sounds fine to me.
