### ISSUE TITLE
Interrupted download results in null manifest

### ISSUE THREAD

**Issue by nicklauslittle-gov** [airpwr/airpwr#95]
If a download gets interrupted, it still gets added to the DB, but as an empty entry. This results in a `null` manifest error when trying to resume the download.

I recommend replacing

```pwsh
	if ([Db]::ContainsKey($k)) {
		$m = [Db]::Get($k)
		$size = $m.Size
	} else {
```

with something like

```pwsh
	if ([Db]::ContainsKey($k) -and ($m = [Db]::Get($k)) -and $m.Size) {
		$size = $m.Size
	} else {
```

in the `PullPackage` method. At least, this solved the issue for me. If there's another solution, I'd be fine with that as well.

**Comment by troyaf** [comment]
Okay. I'll take a look.

**Comment by nicklauslittle** [comment]
Did some more digging on this today. Looks like if the download gets interrupted, then `$locks.Revert()` is called which disposes the `FileStream`, resulting in empty files. I'm submitting a PR that fixes this specific use case. Feel free to expand it if you want to handle something like a corrupt file. (Although, I've never run into that use case yet. Not sure if disposing a `FileStream` will ever partially write a file or not.)
